src/models/base.py
from src.ext import db

class BaseModel(db.Model):

    __abstract__ = True

    def create(self, commit=True):
        db.session.add(self)

        if commit:
            self.save()

    def save(self):
        db.session.commit()

    def delete(self, commit=True):
        db.session.delete(self)

        if commit:
            self.save()

src/models/course.py
from src.models.base import BaseModel
from src.ext import db

class Course(BaseModel):
    __tablename__ = "courses"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    price = db.Column(db.Float)
    prof = db.Column(db.String(100))
    img = db.Column(db.String(300))
    description = db.Column(db.String(1000))
    date = db.Column(db.String(50))

    user_courses = db.relationship("UserCourse", back_populates="course")


    def __repr__(self):
        return self.name

src/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from src.ext import db
from src.models.base import BaseModel


class User (BaseModel, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    email = db.Column(db.String)
    _password = db.Column(db.String)
    profile_img = db.Column(db.String)
    role = db.Column(db.String)

    user_courses = db.relationship("UserCourse", back_populates="user")

    def __repr__(self):
        return self.username


    def check_password(self, password):
        return check_password_hash(self.password, password)

    def is_admin(self):
        return self.role == "Admin"

    #getter
    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = generate_password_hash(password)

src/models/user_course.py
from datetime import datetime
from src.models.base import BaseModel
from src.ext import db

class UserCourse(BaseModel):
    __tablename__ = "users_courses"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    course_id = db.Column(db.Integer, db.ForeignKey("courses.id"))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship("User", back_populates="user_courses")
    course = db.relationship("Course", back_populates="user_courses")

src/views/course/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, FloatField
from flask_wtf.file import FileField, FileSize, FileAllowed

class CourseForm(FlaskForm):
    name = StringField("კურსის სახელი")
    price = FloatField("კურსის ფასი")
    prof = StringField("პროფესორის სახელი")
    img = FileField("პროფესორის ფოტო", validators=[FileSize(1024 * 1024), FileAllowed(["jpg", "png", "jpeg"])])
    date = StringField("კურსის ჩატარების თარიღი")
    description = StringField("კურსის აღწერა")
    submit = SubmitField("კურსის დამატება")

src/__init__.py
from flask import Flask
from flask_admin.menu import MenuLink
from src.config import Config
from src.ext import db, migrate, login_manager, admin
from src.views import main_blueprint, auth_blueprint, course_blueprint
from src.commands import init_db, populate_db
from src.commands import init_db, populate_db
from src.models.user import User
from src.models.course import Course
from src.models.user_course import UserCourse
from src.admin_views.base import SecureModelView
from src.admin_views import CourseView, UserView, UserCourseView

BLUEPRINTS = [main_blueprint, auth_blueprint, course_blueprint]
COMMANDS = [init_db, populate_db]


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    register_extensions(app)
    register_blueprints(app)
    register_commands(app)

    return app


def register_extensions(app):
    # Flask-SQLAlchemy
    db.init_app(app)

    # Flask-Migrate
    migrate.init_app(app, db)

    # Flask-Login
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def load_user(_id):
        return User.query.get(_id)

    # Flask-Admin
    admin.init_app(app)
    admin.add_view(UserView(User, db.session))
    admin.add_view(CourseView(Course, db.session))
    admin.add_view(UserCourseView(UserCourse, db.session))

    admin.add_link(MenuLink("To Site", url="/", icon_type="fa", icon_value="fa-sign-out"))


def register_blueprints(app):
    for blueprint in BLUEPRINTS:
        app.register_blueprint(blueprint)


def register_commands(app):
    for command in COMMANDS:
        app.cli.add_command(command)

src/admin_views/__init__.py
from src.admin_views.course import CourseView
from src.admin_views.user import UserView
from src.admin_views.user_course import UserCourseView

src/views/__init__.py
from src.views.main.routes import main_blueprint
from src.views.auth.routes import auth_blueprint
from src.views.course.routes import course_blueprint

src/views/course/routes.py
from uuid import uuid4
from os import path
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_required, current_user
from src import db
from src.models.user_course import UserCourse
from src.views.course.forms import CourseForm
from src.models.course import Course
from src.config import Config
from src.utils import admin_required

course_blueprint = Blueprint("courses", __name__)

@course_blueprint.route("/add_course", methods=["GET", "POST"])
@admin_required
def add_course():
    form = CourseForm()
    if form.validate_on_submit():
        file = form.img.data
        _, extension = path.splitext(file.filename)
        filename = f"{uuid4()}{extension}"
        file.save(path.join(Config.UPLOAD_PATH, filename))

        new_course = Course(name=form.name.data, price=form.price.data, prof=form.prof.data,
                            img=filename, description=form.description.data, date=form.date.data)
        new_course.create()

        return redirect(url_for("main.index"))

    return render_template("course/add_course.html", form=form)


@course_blueprint.route("/edit_course/<int:id>", methods=["GET", "POST"])
@admin_required
def edit_course(id):
    course = Course.query.get(id)
    form = CourseForm(name=course.name, price=course.price, prof=course.prof, description=course.description, date=course.date)

    if form.validate_on_submit():
        course.name = form.name.data
        course.price = form.price.data
        course.prof = form.prof.data
        course.description = form.description.data
        course.date = form.date.data

        if form.img.data:
            file = form.img.data
            _, extension = path.splitext(file.filename)
            filename = f"{uuid4()}{extension}"
            file.save(path.join(Config.UPLOAD_PATH, filename))

            course.img = filename

        course.save()
        return redirect(url_for("courses.view_course", courses_id=course.id))

    return render_template("course/add_course.html", form=form)


@course_blueprint.route("/delete_course/<int:id>")
@admin_required
def delete_course(id):
    course = Course.query.get(id)
    course.delete()

    return redirect(url_for("main.index"))


@course_blueprint.route("/view/<int:courses_id>")
def view_course(courses_id):
    chosen_course = Course.query.get(courses_id)
    return render_template("course/view_course.html", course=chosen_course)


@course_blueprint.route("/choose_course/<int:course_id>")
@login_required
def choose_course(course_id):
    course = Course.query.get(course_id)

    existing = UserCourse.query.filter_by(user_id=current_user.id, course_id=course.id).first()

    if not existing:
        user_course = UserCourse(user_id=current_user.id, course_id=course.id)
        db.session.add(user_course)
        db.session.commit()
        flash(f"წარმატებით აირჩიე კურსი: {course.name}", "success")
    else:
        flash("კურსი უკვე არჩეულია!", "warning")

    return redirect(url_for("courses.view_course", courses_id=course.id))

src/views/main/routes.py
from flask import Blueprint, render_template
from src.models.course import Course

main_blueprint = Blueprint("main", __name__)

@main_blueprint.route("/")
def index():
    courses = Course.query.all()
    return render_template("main/index.html", courses=courses)

@main_blueprint.route("/about")
def about():
    return render_template("main/about.html")

@main_blueprint.route("/blog")
def blog():
    return render_template("main/blog.html")

@main_blueprint.route("/blogdetails")
def blogdetails():
    return render_template("main/blogdetails.html")

@main_blueprint.route("/career")
def career():
    return render_template("main/career.html")

@main_blueprint.route("/contact")
def contact():
    return render_template("main/contact.html")

src/templates/course/add_course.html
{% extends "partials/base.html" %}

{% block content %}

<div class="header-div" style="display: block; background-color: black;"></div>

<div class="container registration-container">
    <h1>კურსის დამატება</h1>
    <form class="row" method="post" enctype="multipart/form-data">
        {% for errors in form.errors.values() %}
            {% for error in errors %}
                <p class="text-danger"> * {{ error }}</p>
            {% endfor %}
        {% endfor %}
        
        {{ form.hidden_tag() }}

        {{ form.name(placeholder=form.name.label.text, class="form-control") }}
        {{ form.price(placeholder=form.price.label.text, class="form-control") }}
        {{ form.prof(placeholder=form.prof.label.text, class="form-control") }}
        {{ form.img(class="form-control", accept=".jpg, .png, jpeg") }}
        {{ form.description(placeholder=form.description.label.text, class="form-control") }}
        {{ form.date(placeholder=form.date.label.text, class="form-control") }}

        {{ form.submit(class="registration-btn") }}
    </form>
</div>

<script src="/static/scripts/header.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
    crossorigin="anonymous"></script>

{% endblock %}

src/templates/course/view_course.html
{% extends "partials/base.html" %}

{% block content %}

<div class="header-div" style="display: block; background-color: black;"></div>

<!-- Alert regarding course selection -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} show" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="course-info">
    <div class="prof"><img src="/static/upload/{{ course.img }}" alt="Course Professor"></div>
    <div class="course-description">
        <div class="title">{{ course.name }}</div>
        <div class="price">{{ course.price }} ₾</div>
        <div class="prof-name">კურსს გაუძღვება: {{ course.prof }}</div>
        <div class="date">თარიღი: {{ course.date }}</div>
        <div class="course-information">{{ course.description }}</div>
    </div>
</div>

{% if current_user.is_authenticated and current_user.is_admin() %}
    <a href="/edit_course/{{ course.id }}" class="btn btn-primary">კურსის ცვლილება</a>
    <a href="/delete_course/{{ course.id }}" class="btn btn-danger">კურსის წაშლა</a>
{% endif %}

{% if current_user.is_authenticated and not current_user.is_admin() %}
    <a href="{{ url_for('courses.choose_course', course_id=course.id) }}" class="btn btn-success">არჩევა</a>
{% endif %}

<script src="/static/scripts/header.js"></script>

{% endblock %}

src/templates/main/about.html
{% extends "partials/base.html" %}

{% block content %}
<div id="blog-header-div"></div>

<!-- Cover -->
<div class="cover">
    <img src="/static/images/contacts-page-cover.jpg" alt="General-slider">
    <div class="about">
        <h3>აკადემიის შესახებ</h3>
        <p class=""><a href="/">მთავარი</a> &#187; აკადემიის შესახებ</p>
    </div>
</div>

<section class="about-info">
    <h1>ჩვენი ისტორია</h1>
    <p>Future Tech Academy დაარსდა 2025 წელს, სურვილით, მომავალი თაობისთვის ხელმისაწვდომი გაეხადა ტექნოლოგიური
        განათლება. ჩვენი მიზანია, ყველას მიეცეს საშუალება ისწავლოს პროგრამირება, ვებდიზაინი, მონაცემთა ანალიზი და
        სხვა პოპულარული დისციპლინები თანამედროვე მეთოდებით.</p>
    <h1>როგორ ვქმნით საუკეთესო სასწავლო პლატფორმას?</h1>
    <p>ჩვენ გვჯერა, რომ სწავლა უნდა იყოს საინტერესო, ინტერაქტიული და პრაქტიკაზე დაფუძნებული. ამიტომაც ვქმნით:</p>
    <ul class="indented">
        <li>სრულად ინტერაქტიულ კურსებს რეალური პროექტებით</li>
        <li>გამოცდილი მენტორების მხარდაჭერას</li>
        <li>მოსახერხებელ ინტერფეისს ყველა მოწყობილობაზე</li>
        <li>უნიკალურ საგანმანათლებლო მეთოდებს, რომლებიც ერგება როგორც დამწყებებს, ისე პროფესიონალებს</li>
    </ul>
    <p>ჩვენი პლატფორმა მუდმივად ვითარდება, რათა სწავლა უფრო ეფექტური და სასიამოვნო გახდეს.</p>
    <h1>შემოგვიერთდი!</h1>
    <p>Future Tech Academy-ში სწავლა ნიშნავს ინვესტიციას შენს მომავალში. ჩვენს პლატფორმაზე შენი მიზნები ხელშესახები
        ხდება. დაიწყე გზა კარიერისკენ ჩვენთან ერთად – მომავალი უკვე აქ არის!</p>
</section>

<iframe width="700" height="400" src="https://www.youtube.com/embed/enrTLKqMGgo?autoplay=1&mute=1"
    title="YouTube video player" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>

<script src="/static/scripts/header.js"></script>

{% endblock %}

src/templates/main/blog.html
{% extends "partials/base.html" %}

{% block content %}
<div id="blog-header-div"></div>

<!-- Cover -->
<div class="cover">
    <img src="/static/images/contacts-page-cover.jpg" alt="General-slider">
    <div class="blog">
        <h3>ბლოგი</h3>
        <p class=""><a href="/">მთავარი</a> &#187; ბლოგი</p>
    </div>
</div>

<div class="blogs-container" id="blogs-container"></div>

<script src="/static/scripts/header.js"></script>
<script src="/static/scripts/blog.js"></script>

{% endblock %}

src/templates/main/blogdetails.html
{% extends "partials/base.html" %}

{% block content %}
<div id="header-div"></div>

<div id="blog_details_container" class="blog_details_container"></div>

<script src="/static/scripts/header.js"></script>
<script src="/static/scripts/blog_details.js"></script>

{% endblock %}

src/templates/main/career.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <title>Career</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles/css/style.css">
</head>

<body>
    <!-- Cover -->
    <div class="career-cover">
        <h2>Welcome to careers portal</h2>
    </div>

    <h2 class="open-positions">Open positions</h2>

    <!-- Products Container -->
    <div class="container mt-4">
        <div class="row row-col-1" id="jobs-container">
            <!-- Products from API -->
        </div>

        <!-- Pagination -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center mt-4" id="pagination"></ul>
        </nav>
    </div>

    <footer>
        <div class="logo">
            <a href="/" class="main-logo-link">
                <div class="main-logo-footer">
                    <img src="{{ url_for('static', filename='upload/main-logo.png') }}" alt="main logo">
                </div>
            </a>
        </div>
        <p class="footer-logo-name">FutureTech Academy</p>
        <p>მომავლის ტექნოლოგიების აკადემია</p>
        <div class="social-networks">
            <a href="https://www.facebook.com/"><img src="/static/images/soc-networks/fb.PNG" alt="fb"></a>
            <a href="https://www.instagram.com/"><img src="/static/images/soc-networks/instagram.PNG"
                    alt="instagram"></a>
            <a href="https://www.linkedin.com/"><img src="/static/images/soc-networks/linkedin.PNG" alt="linkedin"></a>
            <a href="https://www.youtube.com/"><img src="/static/images/soc-networks/youtube.PNG" alt="youtube"></a>
        </div>
        <p>წესები და პირობები</p>
        <hr>
        <p class="copy">&copy; 2025. საქართველო, თბილისი | ყველა უფლება დაცულია</p>
    </footer>

    <!-- Javascript Code -->
    <script src="/static/scripts/header.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
        crossorigin="anonymous"></script>
    <script src="/static/scripts/career.js"></script>
</body>

</html>

src/templates/main/contact.html
{% extends "partials/base.html" %}

{% block content %}
<div id="blog-header-div"></div>

<!-- Cover -->
<div class="cover">
    <img src="/static/images/contacts-page-cover.jpg" alt="General-slider">
    <div class="contact">
        <h3>კონტაქტი</h3>
        <p class=""><a href="/">მთავარი</a> &#187; კონტაქტი</p>
    </div>
</div>

<form class="contact-form">
    <p>მოგვწერეთ</p>
    <input type="text" name="fullName" id="fullName" placeholder="სახელი და გვარი*">
    <input type="email" name="email" id="email" placeholder="ელ-ფოსტა*">
    <input type="text" name="phoneNumber" id="phoneNumber" placeholder="ტელეფონის ნომერი*"><br>
    <textarea name="message" id="message" placeholder="წერილი"></textarea><br>
    <button>გაგზავნა</button>
</form>

<p class="contact-p">კონტაქტი</p>
<div class="contact-info">
    <div>📍 თბილისი, საქართველო</div>
    <div>📞 +995 555 55 55 55</div>
    <div>📩 futuretechacademy@gmail.com</div>
</div>

<script src="/static/scripts/header.js"></script>

{% endblock %}

src/templates/main/index.html
{% extends "partials/base.html" %}

{% block content %}

<!-- Cover -->
<div class="cover">
    <img src="/static/images/General-slider.png" alt="General-slider">
    <div class="registration">
        {% if not current_user.is_authenticated %}
        <p>დარეგისტრირდი და აირჩიე სასურველი კურსი</p>
        <button class="registration-btn"><a href="/registration">რეგისტრაცია</a></button>
        {% else %}
        <p>დაიწყე გზა კარიერისკენ ჩვენთან ერთად</p>
        <p>აირჩიე სასურველი კურსი</p>
        {% endif %}
    </div>
</div>
<div id="blog-header-div"></div>

<!-- Courses -->
<div class="courses-container">
    <h4>აირჩიე სასურველი კურსი</h4>

    {% if current_user.is_authenticated and current_user.is_admin() %}
    <a href="/add_course" class="btn btn-primary mb-4">კურსის დამატება</a>
    {% endif %}

    <div class="courses">
        {% for course in courses %}
        <a href="/view/{{ course.id }}" class="text-decoration-none text-dark">
            <div class="card overflow-hidden">
                <div class="row g-0">
                    <div class="col-md-6 blue-card">
                        <div class="p-4 mx-auto">
                            <h5 class="fw-bold">{{ course.name }}</h5>
                            <p class="mt-3">{{ course.prof }}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="/static/upload/{{ course.img }}" class="img-fluid h-100 w-100"
                            style="object-fit: cover;" alt="professor">
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

<!-- Script -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
    crossorigin="anonymous"></script>
<script src="/static/scripts/header.js"></script>

{% endblock %}

src/templates/partials/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <title>FutureTech Academy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles/css/style.css">
</head>

{% from "partials/macros.html" import generate_navlink %}

<body>
    <header>
        <a href="/" class="main-logo-link">
            <div class="main-logo">
                <img src="{{ url_for('static', filename='upload/main-logo.png') }}" alt="main logo">
                <p>Future Tech Academy</p>
            </div>
        </a>
        <nav class="menu" id="menu">
            <a href="/">მთავარი</a>
            <a href="/career" target="_blank">კარიერა</a>
            <a href="/blog">ბლოგი</a>
            <a href="/contact">კონტაქტი</a>
            <a href="/about">შესახებ</a>
        </nav>
        {% if current_user.is_authenticated %}
        <nav class="menu profile">
            <a href="{{ url_for('auth.view_profile') }}" class="nav-item"><img src="../../static/images/profile.png"
                    class="profile-icon" alt="profile"></a>
            <a href="/logout">Log Out</a>
        </nav>
        {% else %}
        <nav class="menu">
            <a href="/login">Log In</a>
        </nav>
        {% endif %}

        <div style="display: flex; gap: 15px; align-items: center;">
            <div class="theme-toggle" id="themeToggle">
                <i class="fa-solid fa-moon fa-lg" style="color: #ffffff;"></i>
            </div>
            <div class="burger" id="burger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </header>
    <div class="header-div"></div>

    {% block content %}
    {% endblock %}

    <footer>
        <div class="logo">
            <a href="/" class="main-logo-link">
                <div class="main-logo-footer">
                    <img src="{{ url_for('static', filename='upload/main-logo.png') }}" alt="main logo">
                </div>
            </a>
        </div>

        <p class="footer-logo-name">FutureTech Academy</p>
        <p>მომავლის ტექნოლოგიების აკადემია</p>
        <div class="social-networks">
            <a href="https://www.facebook.com/"><img src="/static/images/soc-networks/fb.PNG" alt="fb"></a>
            <a href="https://www.instagram.com/"><img src="/static/images/soc-networks/instagram.PNG"
                    alt="instagram"></a>
            <a href="https://www.linkedin.com/"><img src="/static/images/soc-networks/linkedin.PNG" alt="linkedin"></a>
            <a href="https://www.youtube.com/"><img src="/static/images/soc-networks/youtube.PNG" alt="youtube"></a>
        </div>
        <p>წესები და პირობები</p>
        <hr>
        <p class="copy">&copy; 2025. საქართველო, თბილისი | ყველა უფლება დაცულია</p>
    </footer>

src/templates/partials/macros.html
{% macro is_active(endpoint_name) %}
    {% if endpoint_name == request.endpoint %}
        active
    {% endif %}
{% endmacro %}

{% macro generate_navlink(name, endpoint) %}
  <a class="nav-link {{ is_active(endpoint) }}"
     href="{{ url_for(endpoint) }}">
    {{ name }}
  </a>
{% endmacro %}